---
- name: Validate if server SQL server or not
  win_shell: sqlcmd -S "{{ target_host }}" -U "{{ db_user }}" -P "{{ db_pass }}" -Q "select @@VERSION"
  register: version_output
 
- debug:
    var: version_output

- name: Reports DB log file growth rate for each database
  win_shell: |    
    sqlcmd -S "{{ target_host }}" -U "{{ db_user }}" -P "{{ db_pass }}"  -Q " SELECT databasename = DB_NAME(dbid),name,fileid,drive = LEFT(filename,1), filename,filegroup = FILEGROUP_NAME(groupid),'size KB' = CONVERT(nvarchar(15), CONVERT(bigint, size) * 8), 'maxsize KB' = (CASE maxsize WHEN-1 THEN N'Unlimited' ELSE CONVERT(nvarchar(15), CONVERT(bigint, maxsize) * 8) END), 'growth' = (CASE status & 0x100000 WHEN 0x100000 THEN CONVERT(nvarchar(15), growth) + N'%' ELSE CONVERT(nvarchar(15), CONVERT(bigint, growth) * 8) END), 'usage' = (CASE status & 0x40 WHEN 0x40 THEN 'log only' ELSE 'data only' END) FROM sys.sysaltfiles ORDER BY drive, size"
  register: dblogfile_growth

- debug:
    var: dblogfile_growth

- set_fact:
    status_code: 2
    version_error: "{{version_output.stderr}}"
  when: version_output is failed

- set_fact:
    status_code: 2
    error_message: "{{dblogfile_growth.stdout_lines}}"
  when: dblogfile_growth is failed
