---
# tasks file for snow_update
#- include_vars: snow_credentials.yml
#  no_log: True

- name: Updating SNOW regarding the failure 
  snow_record:
    username: "{{ username }}"
    password: "{{ password }}"
    instance: "{{ instance_name }}"
    state: present
    number: "{{ snow_incident_id }}"
    data:
      work_notes : "Ansible could not resolve the issue on {{ target_host }} \n Ticket Number {{ snow_incident_id }} \n\n Error Message \n {{ error_msg }}\nAssigning to L2 Support {{ L2_group }}"
      state: "New"
      close_notes: "{{ failure_closing_note }}"
      assignment_group: "{{ L2_group }}"
  vars:
    error_msg: "{{ ansible_failed_result|default('Issue not resolved by Ansible') }}"
  delegate_to: localhost
  become: false
