---
# tasks file for snow_update
#- include_vars: snow_credentials.yml
#  no_log: True

- name: Updating SNOW regarding the failure 
  snow_record:
    username: "{{ username }}"
    password: "{{ password }}"
    instance: "{{ instance_name }}"
    state: present
    number: "{{ snow_incident_id }}"
    data:
      work_notes : "{{ transfer_msg }}"
  delegate_to: localhost
  become: false
