---

- name: Enabling DHCP client
  win_shell: netsh dhcpclient trace enable
  register: dhcp_status

- debug:
    var: dhcp_status

- set_fact:
    status_code: 2
    dhcp_status_error: "{{ dhcp_status.stderr }}" 
  when: dhcp_status is failed
